<?php
	require_once("session.php");
	require_once("database.php");
	require_once("database_object.php");
	require_once("functions.php");
	require_once("calendar.php");
	require_once("nba_calendar.php");
	require_once("player.php");
	require_once("league.php");
	require_once("league_players.php");
	require_once("league_schedule.php");
	require_once("league_standings.php");
	require_once("league_stats.php");
	require_once("league_teams.php");
	require_once("league_login.php");
	require_once("rec_center.php");
	require_once("user_account.php");
	require_once("video.php");
?>